### PR TITLE
Setup teamwork class.

### PR DESCRIPTION
**Pull request by JackAshwell11**
Tasks:
- [x] Input data for Jack.
- [x] Input data for Klevi.

### CODE REVIEW

**Review by JackAshwell11 — COMMENTED** [review]
Looks good

**Comment by 1Klevi1** [comment]
Cool

**Comment by JackAshwell11** [comment]
I can't review it since I made the pull request but I can still override it and merge.

**Comment by 1Klevi1** [comment]
lmao

**Comment by 1Klevi1** [comment]
how can I make it show on my github as well, should i fork it

**Pull request merged**
